<a href="https://colab.research.google.com/github/santhoshjinna15/INFO5731/blob/main/In_class_exercise_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **The second In-class-exercise (1/27/2021, 20 points in total)**


(1) Write a Python program to find the duplicate elements in a given array of integers. Return -1 If there are no such elements. (4 points)

In [8]:
# write your answer here
def duplicates_check(input):
    duplicates_array = []
    array_length=len(input)
    for value in range(array_length):
        next = value + 1
        for num in range(next, len(input)):
            if input[value] == input[num] and input[value] not in duplicates_array:
                duplicates_array.append(input[value])
    if  duplicates_array:
        print("Duplicates are:")
        return duplicates_array
        
    else:
        print("No Duplicates.")
        return -1
    
input_array = [2,3,7,1,25,10,0,5,1,7,2,25,8,10]
print('input-1:')
print(duplicates_check(input_array))

input_array = [1,2,3,7,10,4,5,8]
print('input-2:')
print(duplicates_check(input_array))



input-1:
Duplicates are:
[2, 7, 1, 25, 10]
input-2:
No Duplicates.
-1


(2) Write a Python program to select all the Sundays of a specified year. (4 points)



In [37]:
# write your answer here

from datetime import date, timedelta

def sundays_in_year(input_year):
    jan_1st_year = date(year, 1, 1)      
    jan_1st_year += timedelta(days = 6 - jan_1st_year.weekday())  
    while jan_1st_year.year == input_year:
        yield jan_1st_year
        jan_1st_year += timedelta(days = 7)

input_year = int(input("Enter the year:"))          
for output in sundays_in_year(year):
    print(output)


Enter the year:2022
2021-01-03
2021-01-10
2021-01-17
2021-01-24
2021-01-31
2021-02-07
2021-02-14
2021-02-21
2021-02-28
2021-03-07
2021-03-14
2021-03-21
2021-03-28
2021-04-04
2021-04-11
2021-04-18
2021-04-25
2021-05-02
2021-05-09
2021-05-16
2021-05-23
2021-05-30
2021-06-06
2021-06-13
2021-06-20
2021-06-27
2021-07-04
2021-07-11
2021-07-18
2021-07-25
2021-08-01
2021-08-08
2021-08-15
2021-08-22
2021-08-29
2021-09-05
2021-09-12
2021-09-19
2021-09-26
2021-10-03
2021-10-10
2021-10-17
2021-10-24
2021-10-31
2021-11-07
2021-11-14
2021-11-21
2021-11-28
2021-12-05
2021-12-12
2021-12-19
2021-12-26


(3) Python files reading and writing. Download the “[exercise_02_data _collection.zip](https://github.com/unt-iialab/info5731_spring2021/blob/main/class_exercises/exercise_02_data_collection.zip)” to your local and un-zip it.

*   Write a program to read all the txt files and save the sentences in all the files into one csv file with two columns, the first column is sentence id (txt file name+sentence line number), the second column is the sentence text content. (4 points)
*   Remove all the punctuations from the sentences, save the processed sentences into a new column in the same csv file. (4 points)
*   Ask the user to enter a word, return all the sentences that include this word, three kinds of information should be returned: sentence id, sentence text content, the count that user input word appear in the sentence. (4 points)



In [21]:
# write your answer here

from google.colab import files
data_cltn_ex_2 = files.upload()



Saving ARTHROTEC.1.txt to ARTHROTEC.1 (1).txt
Saving ARTHROTEC.2.txt to ARTHROTEC.2 (1).txt
Saving ARTHROTEC.3.txt to ARTHROTEC.3 (1).txt
Saving ARTHROTEC.4.txt to ARTHROTEC.4 (1).txt
Saving ARTHROTEC.5.txt to ARTHROTEC.5 (1).txt
Saving ARTHROTEC.6.txt to ARTHROTEC.6 (1).txt
Saving ARTHROTEC.7.txt to ARTHROTEC.7 (1).txt
Saving ARTHROTEC.8.txt to ARTHROTEC.8 (1).txt
Saving ARTHROTEC.9.txt to ARTHROTEC.9 (1).txt
Saving ARTHROTEC.10.txt to ARTHROTEC.10 (1).txt
Saving ARTHROTEC.11.txt to ARTHROTEC.11 (1).txt
Saving ARTHROTEC.12.txt to ARTHROTEC.12 (1).txt
Saving ARTHROTEC.13.txt to ARTHROTEC.13 (1).txt
Saving ARTHROTEC.14.txt to ARTHROTEC.14 (1).txt
Saving ARTHROTEC.15.txt to ARTHROTEC.15 (1).txt
Saving ARTHROTEC.16.txt to ARTHROTEC.16 (1).txt
Saving ARTHROTEC.17.txt to ARTHROTEC.17 (1).txt
Saving ARTHROTEC.18.txt to ARTHROTEC.18 (1).txt
Saving ARTHROTEC.19.txt to ARTHROTEC.19 (1).txt
Saving ARTHROTEC.20.txt to ARTHROTEC.20 (1).txt
Saving ARTHROTEC.21.txt to ARTHROTEC.21 (1).txt
Saving ART

In [22]:
import pandas as pd
sentence_id = []
sentence = []
for files in data_cltn_ex_2:
  with open(files, 'r') as file:
    content = file.read()
    split_content = content.splitlines()
    for line_number in range(len(split_content)):
      sentence_id.append(files + '_' +str(line_number))
      sentence.append(split_content[line_number])
df = pd.DataFrame(list(zip(sentence_id, sentence)), 
               columns =['Sentence ID', 'Sentence'])
df.to_csv('output_file.csv', index = False)

In [23]:
import string
df['After Punctuation Removal'] = df['Sentence'].apply(lambda x:''.join([i for i in x 
                                                  if i not in string.punctuation]))
df.to_csv('output_file.csv', index = False)
df

Sentence ID  ...                          After Punctuation Removal
0      ARTHROTEC.1.txt_0  ...  I feel a bit drowsy  have a little blurred vis...
1      ARTHROTEC.1.txt_1  ...  Ive been on Arthrotec 50 for over 10 years on ...
2      ARTHROTEC.1.txt_2  ...  Due to my arthritis getting progressively wors...
3      ARTHROTEC.1.txt_3  ...  every day for the next month to see how I get ...
4      ARTHROTEC.1.txt_4  ...  So far its been very good pains almost gone bu...
..                   ...  ...                                                ...
530  ARTHROTEC.100.txt_3  ...                           canker sores in my mouth
531  ARTHROTEC.100.txt_4  ...                                           headache
532  ARTHROTEC.100.txt_5  ...            been off for 1 week still have bleeding
533  ARTHROTEC.100.txt_6  ...                               helped my pain alot 
534  ARTHROTEC.100.txt_7  ...                 too scared to take this drug again

[535 rows x 3 columns]

(4) Install packages nltk, numpy, scipy, pandas, and sklearn on Google Colab. Write a program to test whether they are installed successfully. (3 points for extra)

In [24]:
# write your answer here


import nltk
nltk.download()


NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all
       | 
       | Downloading package abc to /root/nltk_data...
       |   Unzipping corpora/abc.zip.
       | Downloading package alpino to /root/nltk_data...
       |   Unzipping corpora/alpino.zip.
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Unzipping corpora/biocreative_ppi.zip.
       | Downloading package brown to /root/nltk_data...
       |   Unzipping corpora/brown.zip.
       | Downloading package brown_tei to /root/nltk_data...
       |   Unzipping corpora/brown_tei.zip.
       | Downloading package cess_cat to /root/nltk_data...
       |   Unzipping corpora/cess_cat.zip.
       | Downloading package cess_esp to /root/nltk_data...
 

True

In [25]:
from nltk.tokenize import word_tokenize
output = "test program"
print(word_tokenize(output))

['test', 'program']


In [26]:
pip install numpy


In [28]:
import numpy as np
x =  np.arange(3, 12).reshape(3,3)
print(x)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
pip install scipy

In [30]:
import scipy
print("sciPy - pi = {0}".format(scipy.constants.pi))

sciPy - pi = 3.141592653589793


In [31]:
pip install pandas

In [32]:
import pandas as pd
output = pd.Series(np.array(['a','b','c','d','e']))
print(output)

0    a
1    b
2    c
3    d
4    e
dtype: object


In [33]:
pip install sklearn

In [35]:
from sklearn import datasets
output = datasets.load_digits()
output.target

array([0, 1, 2, ..., 8, 9, 8])